name: CI/CD Cvds Workflow

on:  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar el proyecto con Maven (fase compile)
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas con Maven (fase verify)
        run: mvn verify

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Imprimir mensaje de despliegue
        run: echo "En construcción ..."
