name: CI Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (compile phase)
        run: mvn compile

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set MongoDB URI
        run: echo "SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV

      - name: Run tests (verify phase)
        run: mvn verify

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print deploy message
        run: echo "Desplegando en construcción..."

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laboratorio-reservas:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laboratorio-reservas:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/laboratorio-reservas:latest
            docker stop laboratorio_reservas || true
            docker rm laboratorio_reservas || true
            docker run -d -p 8080:8080 --name laboratorio_reservas \
              --env SPRING_DATA_MONGODB_URI=mongodb://${{ secrets.SERVER_MONGO_HOST }}/laboratorios \
              ${{ secrets.DOCKER_USERNAME }}/laboratorio-reservas:latest
